#ifndef LOG_SETTINGS_HPP
#define LOG_SETTINGS_HPP

#define LEVEL(x) LOG_LEVEL_##x

#define LOG_LEVEL__COMMANDER       LEVEL(DEBUG)
#define LOG_LEVEL__COMMANDS        LEVEL(DEBUG)
#define LOG_LEVEL__RENDERER        LEVEL(DEBUG)

#define LOG_LEVEL__CHANNEL         LEVEL(DEBUG)
#define LOG_LEVEL__COMMAND_PARSER  LEVEL(DEBUG)
#define LOG_LEVEL__IMAGE           LEVEL(DEBUG)

#endif // LOG_SETTINGS_HPP
