include_guard()

if(NOT CMAKE_RUNTIME_OUTPUT_DIRECTORY)
	set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}/_build)
endif()
set(RUNTIME_OUTPUT_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR})
get_filename_component(RUNTIME_OUTPUT_DIRECTORY "${RUNTIME_OUTPUT_DIRECTORY}" ABSOLUTE)
message(STATUS "Output directory: ${RUNTIME_OUTPUT_DIRECTORY}")

if(NOT CMAKE_SIZE)
	set(CMAKE_SIZE size)
endif()
