include_guard()

set(RUNTIME_OUTPUT_DIRECTORY ${CMAKE_RUNTIME_OUTPUT_DIRECTORY})
if(RUNTIME_OUTPUT_DIRECTORY STREQUAL "")
	set(RUNTIME_OUTPUT_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR})
endif()
get_filename_component(RUNTIME_OUTPUT_DIRECTORY "${RUNTIME_OUTPUT_DIRECTORY}" ABSOLUTE)
message(STATUS "Output directory: ${RUNTIME_OUTPUT_DIRECTORY}")
